<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Log;
use App\Models\RefPosition;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $positions = [
            'Administrative Aide IV(Clerk II)',
            'II. CONSTRUCTION AND MAINTENANCE DIVISION:',
            'VII. E. DENTAL SERVICES:',
            '(Management & Audit Analyst IV)',
            '(Supervising AdministrativeOfficer*)',
            'A. ENVIRONMENTAL PROTECTION UNIT:',
            'A. INSPECTION AND CLEANING OPERATIONS UNIT:',
            'Administrative Aide VI (Data Entry Machine Operator I)',
            'Administrative Aide I (Crafts & Trade Helper)',
            'Administrative Aide I (Laborer I)',
            'Administrative Aide I (Utility Worker I)',
            'Administrative Aide I(Laborer I)',
            'Administrative Aide I(Utility Worker I)',
            'Administrative Aide II',
            'Administrative Aide II (Bookbinder I)',
            'Administrative Aide II (Messener)',
            'Administrative Aide II (Messenger)',
            'Administrative Aide II (Reproduction Machine Operator I)',
            'Administrative Aide III',
            'Administrative Aide III ()',
            'Administrative Aide III (Clerk I)',
            'Administrative Aide III (Driver I)',
            'Administrative Aide III (Laborer II)',
            'Administrative Aide III (Toolkeeper)',
            'Administrative Aide III (Utility Worker II)',
            'Administrative Aide III(Clerk I)',
            'Administrative Aide IV',
            'Administrative Aide IV (Bookbinder II)',
            'Administrative Aide IV (Clerk II)',
            'Administrative Aide IV (Driver II)',
            'Administrative Aide IV (Human Resource Mngt. Aide)',
            'Administrative Aide IV (Reproduction Machine Operator II)',
            'Administrative Aide IV (Storekeeper I)',
            'Administrative Aide IV(Clerk II)',
            'Administrative Aide IV(Driver II)',
            'Administrative Aide V (Mason)',
            'Administrative Aide V (Photographer I)',
            'Administrative Aide VI',
            'Administrative Aide VI (Buyer II)',
            'Administrative Aide VI (Clerk III)',
            'Administrative Aide VI (Data Entry Machine Operator I)',
            'Administrative Aide VI (Data Entry Machine OperatorI)',
            'Administrative Aide VI (Data Entry Machine Optr I)',
            'Administrative Aide VI (DEMO I)',
            'Administrative Aide VI (Disbursing Officer I)',
            'Administrative Aide VI (Electronic & Communication Equipment Tech. I)',
            'Administrative Aide VI (Electronic & Communications Equipment Technician)',
            'Administrative Aide VI (Labor Foreman)',
            'Administrative Aide VI (Storekeeper II)',
            'Administrative Aide VI (Utility Foreman)',
            'Administrative Aide VI(Clerk III)',
            'Administrative Assistant I (Bookbinder III)',
            'Administrative Assistant I (Computer Operator I)',
            'Administrative Assistant I (Reproduction Machine Operator III)',
            'Administrative Assistant I(Secretary I)',
            'Administrative Assistant II (Accounting Clerk II)',
            'Administrative Assistant II (Accounting Clerk III)',
            'Administrative Assistant II (Administrative Assistant)',
            'Administrative Assistant II (Assistant Information Officer)',
            'Administrative Assistant II (Bookkeeper I)',
            'Administrative Assistant II (Budgeting Assistant)',
            'Administrative Assistant II (Clerk IV)',
            'Administrative Assistant II (Data Entry Machine Operator II)',
            'Administrative Assistant II (Electronics & Comm. Equipment Technician II)',
            'Administrative Assistant II (Human Resource Mngt. Assistant)',
            'Administrative Assistant II (Instrument Technician A)',
            'Administrative Assistant II (Labor General Foreman)',
            'Administrative Assistant II (Property Custodian)',
            'Administrative Assistant III (Stenographic Reporter II)',
            'Administrative Assistant III (Storekeeper III)',
            'Administrative Assistant V (Data Entry Machine Operator III)',
            'Administrative Assistant V (Data Entry Machine OperatorIII)',
            'Administrative Assistant V (Electronic & Communication Equipment Tech. III)',
            'Administrative Assistant V (Stenographic Reporter III)',
            'Administrative Assistant VI (Computer Operator III)',
            'Administrative Assistant VI (Data Entry Machine OperatorIII)',
            'Administrative Officer I (Cashier I)',
            'Administrative Officer I (Records Officer I)',
            'Administrative Officer I (Supply Officer I)',
            'Administrative Officer I* (Records Officer I)',
            'Administrative Officer II (Administrative Officer I)',
            'Administrative Officer II (Budget Officer I)',
            'Administrative Officer II (Fiscal Examiner I)',
            'Administrative Officer II (Human Resource Mngt. Officer I)',
            'Administrative Officer III (Cashier II)',
            'Administrative Officer III (Records Officer II)',
            'Administrative Officer III (Supply Officer II)',
            'Administrative Officer IV',
            'Administrative Officer IV (Administrative Officer II)',
            'Administrative Officer IV (Budget Officer II)',
            'Administrative Officer IV (Human Resource Mngt. Officer II)',
            'Administrative Officer IV (Information Officer II)',
            'Administrative Officer V (Accountant III)',
            'Administrative Officer V (Admin. Officer III)',
            'Administrative Officer V (Administrative Officer III)',
            'Administrative Officer V (Budget Officer III)',
            'Administrative Officer V (Cashier III)',
            'Administrative Officer V (Fiscal Examiner III)',
            'Administrative Officer V (Human Resource Mngt. Officer III)',
            'Administrative Officer V (Information Officer III)',
            'Administrative Officer V (Supply Officer III)',
            'Administrative Officer V(Cashier III)',
            'ADMINISTRATIVE STAFF:',
            'AdministrativeAssistant III (Sr. Bookkeeper)',
            'AdministrativeOfficer II (Management & Audit Analyst I)',
            'Architect I',
            'Architect II',
            'Architect III',
            'Assessment Clerk I',
            'Assessment Clerk II',
            'Assistant Professor I',
            'Assistant Professor II',
            'Assistant Professor III',
            'Assistant Professor IV',
            'Asssistant Registration Officer',
            'Attorney III',
            'Attorney IV',
            'B. POLLUTION CONTROL AND TESTING UNIT:',
            'B. WATERWAYS AND RIVERWAYS MANAGEMENT UNIT:',
            'Barangay Health Aide',
            'Building Inspector',
            'Building Inspector',
            'CGADH II',
            'CGADH II - Assistant City Engineer',
            'CGADH II - Assistant City General Services Officer',
            'CGADH II - Assistant City Health Officer',
            'CGADH II - Assistant City Social Welfare & Development Officer',
            'CGADH II- Assistant City Assessor',
            'CGADH II- Assistant City Civil Registrar',
            'CGADH II- Assistant City Legal Officer',
            'CGADH II- City Assistant Human Resource Management Officer',
            'CGADH II-Assistant City Planning & Development Coordinator',
            'CGADH II-Assistant City Treasurer',
            'CGADH II-Chief, Business Permits & Licensing Office',
            'CGADH II-Chief,Community & Urban Poor Affairs Office',
            'CGADH II-Chief,Public Safety & Traffic Management Office',
            'CGADH II-City Assistant Accountant',
            'CGADH III- Assistant City Budget Officer',
            'CGADH-Chief, Environmental Management Specialist',
            'CGDH II - City Engineer',
            'CGDH II - City Human Resource Management Officer',
            'CGDH II - City Social Welfare & Development Officer',
            'CGDH II -City Accountant',
            'CGDH II- City Assessor',
            'CGDH II- City Civil Registrar',
            'CGDH II- City Legal Officer',
            'CGDH II-City Administrator',
            'CGDH III - City General Services Officer',
            'CGDH III- City Health Officer',
            'CGDH III- City Treasurer',
            'CGDH III-City Budget Officer',
            'CGDH III-City Planning & Development Coordinator',
            'City Government Assistant Department Head II',
            'City Mayor',
            'City Vice Mayor',
            'CITY YOUTH DEVELOPMENT UNIT',
            'College Administrator',
            'College Librarian',
            'College Librarian I',
            'Community Affairs Assistant I',
            'Community Affairs Assistant II',
            'Community Affairs Officer I',
            'Community Affairs Officer II',
            'Community Affairs Officer III',
            'Community Affairs Officer IV',
            'Computer Maintenance Technologist II',
            'Computer MaintenanceTechnologist I',
            'Computer Programmer I',
            'Computer Programmer II',
            'Construction & Maint. Capataz',
            'Construction & Maint. Foreman',
            'Construction & Maint. Gen. Foreman',
            'Construction & Maintenance Capataz',
            'Construction & Maintenance General Foreman',
            'Construction and Maint. General Foreman',
            'Cooperative Development Specialist II',
            'Day Care Worker II',
            'Dental Aide',
            'Dental Aide',
            'Dentist II',
            'Dentist III',
            'Development Management Officer I',
            'Development Management Officer II',
            'Disability Affairs Assistant',
            'Disability Affairs Officer I',
            'Disability Affairs Officer II',
            'Draftsman I',
            'Draftsman II',
            'Draftsman III',
            'Engineer I',
            'Engineer II',
            'Engineer III',
            'Engineer IV',
            'Engineering Aide',
            'Engineering Assistant',
            'Executive Assistant I',
            'Executive Assistant II',
            'Executive Assistant III',
            'Executive Assistant IV',
            'Fumigator',
            'Guidance Services Specialist I',
            'Handicraft Worker II',
            'Handicraft Worker III',
            'Heavy Equipment Operator',
            'Heavy Equipment Operator III',
            'Housing & Homesite Regulations Assistant',
            'Housing & Homesite Regulations Officer I',
            'Housing & Homesite Regulations Officer III',
            'Housing & Homesite Regulations Officer V',
            'I. A. ACCOUNTING SERVICES DIVISION:',
            'I. A. ARCHITECTURAL SECTION:',
            'I. A. BARANGAY AFFAIRS SECTION:',
            'I. A. BOOKKEEPING SECTION:',
            'I. A. CHILD DEVELOPMENT & PROTECTION SECTION:',
            'I. A. CITY SECURITY SECTION:',
            'I. A. INFORMATION TECHNOLOGY SOFTWARE MANAGEMENT SECTION:',
            'I. A. MARRIAGE SECTION:',
            'I. A. PERMIT RECORD SECTION:',
            'I. A. PROCUREMENT SECTION:',
            'I. A. RESEARCH & DATA BANK SECTION:',
            'I. A. TRAINING SECTION:',
            'I. ADMINISRTATIVE AND TRAINING SECTION',
            'I. ADMINISTRATIVE STAFF:',
            'I. B. ALLOCATION AND ALLOTMENT SECTION:',
            'I. B. BIRTH AND DEATH DIVISION:',
            'I. B. CIVIL SECTION:',
            'I. B. CUSTODIAN, ACCOUNTABILITY & DISPOSAL SECTION:',
            'I. B. INFORMATION TECHNOLOGY HARDWARE MANAGEMENT SECTION:',
            'I. B. LAND APPRAISAL SECTION:',
            'I. B. REMITTANCE SECTION:',
            'I. B. SANITARY ENFORCEMENT SECTION:',
            'I. B. SOCIAL DEVELOPMENT & ENVIRONMENTAL MANAGEMENT',
            'I. B. TRAINING UNIT:',
            'I. B. WOMEN,FAMILY AND COMMUNITY SECTION:',
            'I. BIRTH, MARRIAGE AND DEATH DIVISION:',
            'I. BUDGET ALLOCATION AND INTERNAL AFFAIRS DiVISION:',
            'I. C. PUBLIC ORDER, SAFETY & INTELLIGENCE:',
            'I. C. VETERINARY SECTION:',
            'I. CAPABILITY BUILDING UNIT:',
            'I. CASH DIVISION:',
            'I. CHILD, FAMILY AND COMMUNITY WELFARE DIVISION:',
            'I. COMMUNITY & BARANGAY AFFAIRS DIVISION:',
            'I. EMPLOYMENT ASSISTANCE UNIT:',
            'I. HUMAN RESOURCE DEVELOPMENT TRAINING & EVALUATION DIVISION:',
            'I. LICENSING DIVISION:',
            'I. MANAGEMENT INFORMATION SERVICES DIVISION:',
            'I. MANPOWER DEVELOPMENT SECTION:',
            'I. MANPOWER TESTING UNIT:',
            'I. MARKET ADMINISTRATION SECTION:',
            'I. PLANNING DIVISION:',
            'I. PROPERTY & SUPPLIES MANAGEMENT DIVISION:',
            'I. PROPERTY APPRAISAL DIVISION:',
            'I. PUBLIC ORDER & SAFETY DIVISION:',
            'I. RESEARCH AND INFORMATION SECTION:',
            'I. SPORTS DEVELOPMENT UNIT;',
            'I. TECHNICAL SERVICES SECTION:',
            'I. TRIAL AND INVESTIGATION DIVISION:',
            'I. VETERINARY & SANITATION SERVICES DIVISION:',
            'I. WASTE MANAGEMENT SECTION:',
            'I.A. BUDGET EVALUATION AND INTEGRATION SECTION:',
            'I.A. BUILDING & MACHINERY APPRAISAL SECTION:',
            'I.A. BUSINESS & OCCUPATIONAL PERMIT SECTION:',
            'I.B. ELECTRONIC DATA PROCESSING & ASSESSMENT SECTION:',
            'I.B. ENVIRONMENTAL ENFORCEMENT SECTION:',
            'I.B. EVALUATION SECTION:',
            'I.B.COMMUNITY RELATIONS SECTION:',
            'II. A. ADMINISTRATIVE AFFAIRS SECTION:',
            'II. A. BARITAN I HEALTH CENTER:',
            'II. A. BUDGET REVIEW SECTION:',
            'II. A. CONSTRUCTION SECTION:',
            'II. A. DISASTER RELIEF AND ASSISTANT SECTION:',
            'II. A. INSTITUTIONAL DEVELOPMENT SECTION:',
            'II. A. INTERNAL AUDITING SECTION:',
            'II. A. RECEIVING AND RELEASING SECTION:',
            'II. A. SELECTION AND SCREENING SECTION:',
            'II. A. TAXMAPPING SECTION:',
            'II. A. TRAINEE ASSISTANCE UNIT:',
            'II. ADMINISTRATIVE AFFAIRS DIVISION:',
            'II. APPOINTMENT AND COUNSELLING DIVISION:',
            'II. B. BARITAN II HEALTH CENTER:',
            'II. B. DISADVANTAGED INDIVIDUALS AND CRISIS INTERVENTION SECTION:',
            'II. B. DOCUMENTS VERIFICATION, ORIENTATION AND COUNSELLING SECTION:',
            'II. B. EXTERNAL AFFAIRS SECTION:',
            'II. B. FINANCIAL MANAGEMENT SECTION:',
            'II. B. INDUSTRIAL RELATION UNIT:',
            'II. B. LIAISON AND NETWORKING SECTION:',
            'II. B. LOCATIONAL CLEARANCE APPLICATION RECEIVING & RELEASING SECTION:',
            'II. B. MAINTENANCE SECTION:',
            'II. B. RECORDS CUSTODY AND BOOKBINDING SECTION:',
            'II. B. RECORDS KEEPING, ARCHIVES AND DISPOSAL SECTION:',
            'II. B. TRAFFIC OPERATION SECTION:',
            'II. BUDGET REVIEW AND EXTERNAL AFFAIRS DIVISION:',
            'II. C. BAYAN-BAYANAN HEALTH CENTER:',
            'II. CENTRAL RECORDS MANAGEMENT & ARCHIVES DIVISION:',
            'II. CITY MAIN LIBRARY:',
            'II. COMMUNITY SERVICES SECTION',
            'II. COUNSELLING & DOCUMENTATION DIVISION:',
            'II. D. CATMON HEALTH CENTER:',
            'II. E. CONCEPCION PUERICULTURE CENTER:',
            'II. E. DAMPALIT PUERICULTURE CENTER:',
            'II. ENVIRONMENTAL MANAGEMENT SECTION:',
            'II. F. FLORES HEALTH CENTER:',
            'II. FINANCIAL MANAGEMENT & INTERNAL AUDIT DIVISION:',
            'II. G. HULONG-DUHAT PUERICULTURE CENTER :',
            'II. HEALTH OPERATIONAL SERVICES:',
            'II. I. LONGOS BAGONG LIPUNAN CENTER:',
            'II. INSPECTION/ ENFORCEMENT DIVISION:',
            'II. J. MAYSILO HEALTH CENTER:',
            'II. K. MUZON PUERICULTURE CENTER:',
            'II. L. NIUGAN PUERICULTURE CENTER:',
            'II. LABOR RELATIONS UNIT:',
            'II. LAND USE MANAGEMENT & ZONING DIVISION:',
            'II. M. ACACIA PUERICULTURE CENTER:',
            'II. MAINTENANCE AND ENFORCEMENT SECTION:',
            'II. MANAGEMENT AND DEVELOPMENT UNIT:',
            'II. MEDIA RELATIONS SECTION:',
            'II. N. PANGHULO HEALTH CENTER:',
            'II. O. POTRERO PUERICULTURE CENTER:',
            'II. P. DURIAN HEALTH CENTER:',
            'II. Q. SAN AGUSTIN HEALTH CENTER:',
            'II. R. SANTULAN HEALTH CENTER:',
            'II. RECORDS DIVISION:',
            'II. RESEARCH AND PLANNING SECTION:',
            'II. S. TINAJEROS PUERICULTURE CENTER:',
            'II. SOCIAL UPLIFTMENT SERVICES DIVISION:',
            'II. SPORTS FACILITIES OPERATIONS UNIT:',
            'II. T. TONSUYA PUERICULTURE CENTER:',
            'II. TAXMAPPING DIVISION:',
            'II. TRAFFIC MANAGEMENT DIVISION:',
            'II. TRAINEE ASSISTANCE/ INDUSTRIAL RELATIONS SECTION:',
            'II. U. TUGATOG PUERICULTURE CENTER:',
            'II. URBAN POOR AFFAIRS DIVISION:',
            'II. V. MALABON PUERICULTURE CENTER:',
            'II. W. TAÑONG (EXT.) HEALTH CENTER:',
            'II.A. ENFORCEMENT/MONITORING SECTION:',
            'II.A. GENERAL UTILITY SERVICES SECTION:',
            'II.A. RECEIVING, RELEASING AND PROCESSING SECTION:',
            'II.A. SURVEY & CENSUS SECTION:',
            'II.A. TOWING OPERATION SECTION:',
            'II.B. RECORDS SECTION:',
            'II.B. URBAN POOR ORGANIZING & ASSISTANCE SECTION:',
            'II.C. INSPECTION, EVALUATION AND MAPPING SECTION;',
            'II.C. PARKING REGULATORY SECTION:',
            'II.H. IBABA BAGONG LIPUNAN CENTER:',
            'III. A. ASSESSMENT ROLL SECTION:',
            'III. A. FISCAL PLANNING AND MONITORING SECTION:',
            'III. A. FLOOD CONTROL DIVISION:',
            'III. A. FLOOD CONTROL SYSTEM SECTION:',
            'III. A. MANAGEMENT UNIT:',
            'III. A. MONITORING APPEALS SECTION:',
            'III. A. WELFARE SERVICES SECTION:',
            'III. ASSESSMENT RECORDS DIVISION:',
            'III. AUDIO-VISUAL SECTION:',
            'III. B. CEMETERY RECORDS UNIT:',
            'III. B. DATABASE SECTION:',
            'III. B. ELECTRONIC DATA PROCESSING SECTION:',
            'III. B. LAND TENURIAL PROJECTS SECTION:',
            'III. B. LEAVE ADMINISTRATION SECTION:',
            'III. B. OPERATIONS AND MONITORING SECTION:',
            'III. BUILDING & GROUNDS ADMINISTRATION & MAINTENANCE DIVISION:',
            'III. C. REPAIR & MAINTENANCE SERVICE SECTION:',
            'III. C. SOCIAL HOUSING AND OTHER HOUSING PROJECTS SECTION:',
            'III. CEMETERY MANAGEMENT SECTION:',
            'III. CITY LIBRARY AT HULONG-DUHAT (ANNEX)',
            'III. CONSUMER PROTECTION SECTION:',
            'III. EMPLOYEES WELFARE SERVICES DIVISION:',
            'III. ESTATE MANAGEMENT & DEVELOPMENT DIVISION:',
            'III. FISCAL,PLANNING,MONITORING AND DATA BASE DIVISION:',
            'III. I. DIETARY:',
            'III. MALABON ANTI-DRUG CENTER ( Drug Abuse)',
            'III. OPERATION AND WARNING SECTION:',
            'III. REAL PROPERTY TAX DIVISION:',
            'III.B. ADMINISTRATIVE STAFF: (Extension of Administrative-Health Department)',
            'III.B. PARKS AND GROUNDS MAINTENANCE SECTION:',
            'Information System Researcher I',
            'Information System Researcher II',
            'Information Technology Officer II',
            'Instructor I',
            'Instructor III',
            'Instrumentman',
            'Internal Auditing Assistant',
            'Internal Auditor I',
            'Internal Auditor II',
            'IV. A. PAYROLL/VOUCHERS PREPARATIONS SECTION:',
            'IV. B. PERSONNEL TRANSACTION AND RECORDS SECTION:',
            'IV. BUILDING PERMIT PROCESSING DIVISION',
            'IV. MOTORPOOL SECTION:',
            'IV. NUTRITION SERVICES DIVISION:',
            'IV. PERSONNEL TRANSACTION, RECORDS AND PAYROLL PREPARATIONS DIVISION:',
            'IV.-A. Architectural Line & Grade Section:',
            'IV.-B. General Engineering Section:',
            'l. C. ECONOMICAL DEVELOPMENT SECTION;',
            'Labor & Employment Officer II',
            'Laboratory Aide II',
            'Laboratory Technician',
            'Legal Assistant I',
            'LEGISLATIVE SERVICES SECTION',
            'Librarian I',
            'Librarian II',
            'Librarian III',
            'Librarian IV',
            'License Inspector I',
            'Licensing Officer I',
            'Licensing Officer II',
            'Licensing Officer III',
            'Livestock Inspector II',
            'Local Assessment Operations Officer I',
            'Local Assessment Operations Officer II',
            'Local Assessment Operations Officer III',
            'Local Assessment Operations Officer IV',
            'Local Disaster Risk Reduction and Mngt. Assistant',
            'Local Disaster Risk Reduction and Mngt. Officer I',
            'Local Disaster Risk Reduction and Mngt. Officer II',
            'Local Disaster Risk Reduction and Mngt. Officer III',
            'Local Treasury Operations Officer I',
            'Local Treasury Operations Officer II',
            'Local Treasury Operations Officer III',
            'Local Treasury Operations Officer IV',
            'Manpower Development Assistant',
            'Manpower Development Officer I',
            'Market Supervisor I',
            'Market Supervisor IV',
            'Master Tailor II',
            'Meat Inspector I',
            'Mechanic Technician II',
            'Medical Officer III',
            'Medical Officer IV',
            'Medical Officer V',
            'Medical Technologist I',
            'Medical Technologist II',
            'Medical Technologist I',
            'Medical Technologist II',
            'Midwife II',
            'Midwife III',
            'Nurse Attendant I',
            'Nurse I',
            'Nurse I (former Nurse II)',
            'Nurse II',
            'Nurse III',
            'Nurse IV',
            'Nutrition Dietitian II',
            'Nutrition Officer III',
            'Nutritionist-Dietitian II',
            'Parking Aide I',
            'Parking Aide II',
            'Personal Driver',
            'Pharmacist II',
            'Planning Officer I',
            'Planning Officer II',
            'Planning Officer IV',
            'Population Program Officer I',
            'Population Program Officer III',
            'Private Secretary I',
            'Private Secretary II',
            'Process Server',
            'Project Development Assistant',
            'Project Development Assistant II (Public Relations Officer I)',
            'Project Development Officer II',
            'Project Evaluation Officer II',
            'Public Services Officer I',
            'Public Services Officer II',
            'Public Services Officer III',
            'Public Services Officer IV',
            'Radiologic Technologist I',
            'Radiologic Technologist II',
            'Registration Officer II',
            'Registration Officer III',
            'Registration Officer IV',
            'Revenue Collection Clerk II',
            'Revenue Collection Clerk III',
            'Sangguniang Panlungsod Member II',
            'Sanitation Inspector I',
            'Sanitation Inspector III',
            'Sanitation Inspector V',
            'Sanitation Inspector VI',
            'Secretary to the Sangguniang Panlungsod',
            'Security Agent I',
            'Security Agent II',
            'Security Guard I',
            'Security Officer I',
            'Security Officer II',
            'Security Officer III',
            'Security Officer IV',
            'Senior Cooperative Development Specialist',
            'Senior Labor & Employment Officer III',
            'Senior Manpower Development Officer',
            'Social Welfare Assistant',
            'Social Welfare Assistant',
            'Social Welfare Assistant I',
            'Social Welfare Officer I',
            'Social Welfare Officer II',
            'Social Welfare Officer III',
            'Social Welfare Officer IV',
            'Sports & Games Regulation Officer I',
            'Sports Development Officer I',
            'Sports Development Officer III',
            'Sr. Environmental Management Specialist',
            'Supervising Administrative Officer (Human Resource Mngt. Officer IV)',
            'Supervising Manpower Development Officer',
            'Supervising Administrative Officer (Administrative Officer IV)',
            'Supervising Administrative Officer (Budget Officer IV)',
            'Supervising Administrative Officer (Cashier IV)',
            'Supervising Administrative Officer (Human Resource Mngt. Officer IV)',
            'Supervising Administrative Officer (Information Officer IV)',
            'Supervising Administrative Officer (Records Officer IV)',
            'Supervising Administrative Officer (Supply Officer IV)',
            'Supervising AdministrativeOfficer (Accountant IV)',
            'Supervising AdministrativeOfficer (Administrative Officer IV)',
            'Tax Mapper II',
            'Tax Mapper III',
            'Tax Mapper IV',
            'Tax Mapping Aide',
            'Toolkeeper',
            'Tourism Operations Assistant',
            'Tourism Operations Officer I',
            'Tourism Operations Officer II',
            'Traffic Aide',
            'Traffic Operations Officer I',
            'Traffic Operations Officer II',
            'Traffic Operations Officer IV',
            'University President',
            'University Researcher IV',
            'University Secretary',
            'V. A. OPT-FEEDING, SPECIAL PROJECTS & REHABILITATION SECTION:',
            'V. ENFORCEMENT DIVISION:',
            'Veterinarian II',
            'VI. B. FAMILY PLANNING COUNSELLING DIVISION:',
            'VI.-A. Inspection Section:',
            'VI.-B. Apprehension/Complaints Section:',
            'Vice President for Academic Affairs',
            'Vice President for Administration',
            'VII. B. MEDICAL SERVICES:',
            'VII. D. NURSING/MIDWIFERY SERVICES:',
            'VII. D. PARAMEDICAL SERVICES: (PHARMACY)',
            'VII. E. MEDICAL SOCIAL WORK SERVICES:',
            'VII. F. CLINICAL LABORATORY :',
            'VII. G. RADIOLOGIC:',
            'VII. OSPITAL NG MALABON (Formerly Pagamutang Bayan ng Malabon)',
            'Welder',
            'Welder I',
            'Youth Development Officer II',
            'Zoning Inspector I',
            'Zoning Officer I',
            'Zoning Officer II',
            'Zoning Officer IV',
        ];

        // filter
        $toBeRemoved = [
            'X.', 'IX.', 'VIIII.', 'VII.', 'VI.', 'V.', 'IV.', 'III.', 'II.', 'I.',
            'A.', 'B.', 'C.', 'D.', 'E.', 'F.', 'G.', 'H.', 'I.', 'J.', 'K.'
        ];
        $tbrLen = count($toBeRemoved);

        for ($i = 0; $i < count($positions); $i++) {

            do {
                $removeHappens = false;

                foreach ($toBeRemoved as $str) {
                    if (strpos($positions[$i], $str) === 0) {
                        $positions[$i] = trim(substr($positions[$i], strlen($str)));

                        // remove hypen at start of string
                        if ($positions[$i][0] == '-') {
                            $positions[$i] = trim(substr($positions[$i], 1));
                        }

                        $removeHappens = true;
                        break;
                    }
                }

            } while ($removeHappens);
        }

        // remove the parenthesis if starts with that
        for ($i = 0; $i < count($positions); $i++) {
            if ($positions[$i][0] == '(' && $positions[$i][-1] == ')') {
                $positions[$i] = trim(substr($positions[$i], 1, -1));
            }
        }

        // remove special chars at end
        for ($i = 0; $i < count($positions); $i++) {
            if (in_array($positions[$i][-1], [':', '*'])) {
                $positions[$i] = trim(substr($positions[$i], 0, -1));
            }
        }

        // str to sentence case except roman numerals
        $pattern = '/\b(?![LXIVCDM]+\b)([A-Z]+)\b/';

        for ($i = 0; $i < count($positions); $i++) {
            $positions[$i] = preg_replace_callback($pattern, function($matches) {
                return ucfirst(strtolower($matches[0]));
            }, $positions[$i]);
        }

        // order alphabetically
        sort($positions);

        // insert
        foreach ($positions as $position) {
            RefPosition::create([
                'position_name' => $position
            ]);
        }
    }
}
